name: New release
description: Checklist for creating a new release of the OSPS Baseline
title: "[Release]: "
body:
  - type: markdown
    attributes:
      value: |
        This issue type is for maintainer use. If you need to file an issue, use the "Blank issue" type.
  - type: input
    id: version
    attributes:
      label: Version
      description: New version to release
      placeholder: e.g. 2025-02-04
  - type: checkboxes
    id: checklist
    attributes:
      label: Release checklist
      options:
        - label: |
            Ensure all pull requests targeted for this release are merged
        - label: |
            Update `docs/release_notes.md` with the changes in this release
        - label: |
            Run: `make release VERSION=<VERSION>` (replace `<VERSION>` with the version, e.g. `2026-04-04`)
        - label: |
            Review the diff to confirm the generated files look correct
        - label: |
            Open a pull request with the above changes
        - label: |
            After the pull request is merged, git tag the commit
        - label: |
            After the pull request is merged, send an email to the [mailing list](https://lists.openssf.org/g/openssf-sig-security-baseline)
        - label: |
            After the pull request is merged, notify OpenSSF's marketing team
